version: "3.8"
services:
  mysql:
    image: mysql:8.0.42
    container_name: mysql
    ports:
#      - "3306:3306"
      - "3307:3306"
    environment:
      MYSQL_ROOT_USERNAME: root
#      MYSQL_ROOT_PASSWORD: Onida@313
#      MYSQL_ROOT_DATABASE: order_service
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql