#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Onida@313
##    url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
#    url: jdbc:mysql://localhost:3306/order_service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver


