
spring:
  application:
    name: Order-Service
  profiles:
    #    active: dev
    #    active: qa
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
#  flyway:
#    enabled: true

server:
  port: 8082

